# Generated by Django 4.2.5 on 2023-09-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
